/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package First.picture;

/**
 *
 * @author skrikeshut
 */
public class Calculator extends javax.swing.JFrame {

    double avg;
    double obs;
    double whip;
    double obaa;
    double pit = (whip+obaa)*26;
    double batt = avg + obs;
    double calc = (int)(batt/pit);
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pitch = new javax.swing.JLabel();
        bat = new javax.swing.JLabel();
        cKl = new javax.swing.JLabel();
        mLe = new javax.swing.JLabel();
        mMo = new javax.swing.JLabel();
        cKLB = new javax.swing.JButton();
        mLeB = new javax.swing.JButton();
        jAl = new javax.swing.JLabel();
        mMoB = new javax.swing.JButton();
        mMou = new javax.swing.JLabel();
        jBa = new javax.swing.JLabel();
        jAlB = new javax.swing.JButton();
        mMouB = new javax.swing.JButton();
        jBaB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        pitch.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        pitch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pitch.setText("Pitchers");
        getContentPane().add(pitch);
        pitch.setBounds(150, 30, 220, 80);

        bat.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        bat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bat.setText("Batters");
        getContentPane().add(bat);
        bat.setBounds(400, 30, 220, 80);

        cKl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cKl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/446372.jpg"))); // NOI18N
        getContentPane().add(cKl);
        cKl.setBounds(100, 100, 90, 120);

        mLe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/502190.jpg"))); // NOI18N
        getContentPane().add(mLe);
        mLe.setBounds(100, 225, 90, 120);

        mMo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mMo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/519043.jpg"))); // NOI18N
        mMo.setToolTipText("");
        getContentPane().add(mMo);
        mMo.setBounds(100, 340, 90, 120);

        cKLB.setText("Corey Kluber");
        cKLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKLBActionPerformed(evt);
            }
        });
        getContentPane().add(cKLB);
        cKLB.setBounds(200, 150, 120, 23);

        mLeB.setText("Mike Leake");
        mLeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLeBActionPerformed(evt);
            }
        });
        getContentPane().add(mLeB);
        mLeB.setBounds(200, 280, 120, 23);

        jAl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/514888.jpg"))); // NOI18N
        getContentPane().add(jAl);
        jAl.setBounds(575, 100, 90, 120);

        mMoB.setText("Matt Moore");
        mMoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMoBActionPerformed(evt);
            }
        });
        getContentPane().add(mMoB);
        mMoB.setBounds(200, 390, 120, 23);

        mMou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mMou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/519058.jpg"))); // NOI18N
        getContentPane().add(mMou);
        mMou.setBounds(575, 225, 90, 120);

        jBa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/430832.jpg"))); // NOI18N
        getContentPane().add(jBa);
        jBa.setBounds(575, 340, 90, 120);

        jAlB.setText("Jose Altuve");
        jAlB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlBActionPerformed(evt);
            }
        });
        getContentPane().add(jAlB);
        jAlB.setBounds(450, 150, 120, 23);

        mMouB.setText("Mike Moustakas");
        mMouB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMouBActionPerformed(evt);
            }
        });
        getContentPane().add(mMouB);
        mMouB.setBounds(450, 280, 120, 23);

        jBaB.setText("Jose Bautista");
        jBaB.setToolTipText("");
        jBaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaBActionPerformed(evt);
            }
        });
        getContentPane().add(jBaB);
        jBaB.setBounds(450, 390, 120, 23);

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 500, 250, 22);

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(425, 500, 250, 22);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 430, 90, 23);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 480, 50, 50);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/picture/Hvtxo6m.jpg"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(-2, -5, 810, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cKLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKLBActionPerformed
        jLabel2.setText("against Corey Kluber");
        
        double whip = 0.87;
        double obaa = 0.193;
        
        pitcher(whip, obaa);
    }//GEN-LAST:event_cKLBActionPerformed

    private void jAlBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlBActionPerformed
        jLabel1.setText("Jose Altuve has a");
        
        double avg = 0.346;
        double obs = 0.410;
        
        batter(avg, obs);
    }//GEN-LAST:event_jAlBActionPerformed

    private void mMouBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMouBActionPerformed
        jLabel1.setText("Mike Moustakas has a");
        
        double avg = 0.272;
        double obs = 0.314;
        
        batter(avg, obs);
    }//GEN-LAST:event_mMouBActionPerformed

    private void jBaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaBActionPerformed
        jLabel1.setText("Jose Bautista has a");
        
        double avg = 0.203;
        double obs = 0.308;
        
        batter(avg, obs);
    }//GEN-LAST:event_jBaBActionPerformed

    private void mLeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLeBActionPerformed
        jLabel2.setText("against Mike Leake");
        
        double whip = 1.28;
        double obaa = 0.278;
        
        pitcher(whip, obaa);
    }//GEN-LAST:event_mLeBActionPerformed

    private void mMoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMoBActionPerformed
        jLabel2.setText("against Matt Moore");
        
        double whip = 1.53;
        double obaa = 0.283;
        
        pitcher(whip, obaa);
    }//GEN-LAST:event_mMoBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel3.setText(String.valueOf(((whip+obaa)*26)/(avg+obs)));
    }//GEN-LAST:event_jButton1ActionPerformed

    public void batter(double a, double o)
    {
        avg = a;
        obs = o;
    }
    
    public void pitcher(double w, double s)
    {
        whip = w;
        obaa = s;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bat;
    private javax.swing.JButton cKLB;
    private javax.swing.JLabel cKl;
    private javax.swing.JLabel jAl;
    private javax.swing.JButton jAlB;
    private javax.swing.JLabel jBa;
    private javax.swing.JButton jBaB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mLe;
    private javax.swing.JButton mLeB;
    private javax.swing.JLabel mMo;
    private javax.swing.JButton mMoB;
    private javax.swing.JLabel mMou;
    private javax.swing.JButton mMouB;
    private javax.swing.JLabel pitch;
    // End of variables declaration//GEN-END:variables
}
